### ISSUE TITLE
good job! 现在@change事件其实叫@input更合适, 现在的change事件太频繁了,现在怎么处理失去焦点并且数值改变呢?

### ISSUE THREAD

**Issue by yp199618** [Jeddy-2020/vue-thousandth-input#1]
good job! 现在@change事件其实叫@input更合适, 现在的change事件太频繁了,现在怎么处理失去焦点并且数值改变呢?

**Comment by jeddygong** [comment]
叫@input会有冲突，白天在工作，今晚更新，失去焦点事件

**Comment by jeddygong** [comment]
> good job! 现在@change事件其实叫@input更合适, 现在的change事件太频繁了,现在怎么处理失去焦点并且数值改变呢?

最新版v0.1.2已更新
